/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package io.github.yuroyami.kitejs

/**
 * Whole programs from `jvmTest/resources/eval`, each with the answer upstream Rhino gives.
 * Generated from the corpus files; `EvalCorpusSliceOracleTest` fails when either side drifts.
 */
object EvalCorpusSlice {

    class Program(val name: String, val source: String, val expected: String)

    val programs: List<Program> = listOf(
        Program(
            "closures_counter",
            "// Independent counters, each with its own captured state.\nfunction makeCounter(start) {\n  var count = start;\n  return {\n    inc: function () { return ++count; },\n    dec: function () { return --count; },\n    get: function () { return count; }\n  };\n}\nvar a = makeCounter(10), b = makeCounter(100);\na.inc(); a.inc(); b.dec();\nvar log = [];\nlog.push(a.get(), b.get(), a.inc() + b.inc());\nvar adders = [];\nfor (var i = 0; i < 3; i++) {\n  adders.push((function (n) { return function (x) { return x + n; }; })(i));\n}\nlog.push(adders[0](10), adders[1](10), adders[2](10));\nlog.join(',');\n",
            "12,99,113,10,11,12",
        ),
        Program(
            "recursion",
            "function fact(n) { return n <= 1 ? 1 : n * fact(n - 1); }\nvar memo = {};\nfunction fib(n) {\n  if (n < 2) return n;\n  if (memo[n] !== undefined) return memo[n];\n  return memo[n] = fib(n - 1) + fib(n - 2);\n}\nfunction ack(m, n) {\n  if (m === 0) return n + 1;\n  if (n === 0) return ack(m - 1, 1);\n  return ack(m - 1, ack(m, n - 1));\n}\nfunction gcd(a, b) { return b === 0 ? a : gcd(b, a % b); }\nfunction hanoi(n, from, to, via, moves) {\n  if (n === 0) return moves;\n  hanoi(n - 1, from, via, to, moves);\n  moves.push(from + '>' + to);\n  return hanoi(n - 1, via, to, from, moves);\n}\nfunction sumDigits(n) { return n < 10 ? n : (n % 10) + sumDigits(Math.floor(n / 10)); }\n[fact(10), fib(40), ack(2, 3), gcd(1071, 462), hanoi(3, 'A', 'C', 'B', []).join(' '), sumDigits(987654321)].join('|');\n",
            "3628800|102334155|9|21|A>C A>B C>B A>C B>A B>C A>C|45",
        ),
        Program(
            "sorting_algorithms",
            "var input = [33, 7, -2, 19, 7, 0, 100, -50, 42, 3, 8, 8, 1];\nfunction bubble(a) {\n  a = a.slice();\n  for (var i = 0; i < a.length; i++)\n    for (var j = 0; j < a.length - i - 1; j++)\n      if (a[j] > a[j + 1]) { var t = a[j]; a[j] = a[j + 1]; a[j + 1] = t; }\n  return a;\n}\nfunction insertion(a) {\n  a = a.slice();\n  for (var i = 1; i < a.length; i++) {\n    var v = a[i], j = i - 1;\n    while (j >= 0 && a[j] > v) { a[j + 1] = a[j]; j--; }\n    a[j + 1] = v;\n  }\n  return a;\n}\nfunction quick(a) {\n  if (a.length <= 1) return a;\n  var pivot = a[0], left = [], right = [];\n  for (var i = 1; i < a.length; i++) (a[i] < pivot ? left : right).push(a[i]);\n  return quick(left).concat([pivot], quick(right));\n}\nfunction merge(a) {\n  if (a.length <= 1) return a;\n  var mid = a.length >> 1;\n  var l = merge(a.slice(0, mid)), r = merge(a.slice(mid)), out = [];\n  while (l.length && r.length) out.push(l[0] <= r[0] ? l.shift() : r.shift());\n  return out.concat(l, r);\n}\nvar builtin = input.slice().sort(function (x, y) { return x - y; });\nvar lexical = input.slice().sort();\nvar all = [bubble(input), insertion(input), quick(input), merge(input)];\nvar agree = all.every(function (a) { return a.join() === builtin.join(); });\n[builtin.join(' '), lexical.join(' '), agree, input.join(' ')].join('|');\n",
            "-50 -2 0 1 3 7 7 8 8 19 33 42 100|-2 -50 0 1 100 19 3 33 42 7 7 8 8|true|33 7 -2 19 7 0 100 -50 42 3 8 8 1",
        ),
        Program(
            "string_processing",
            "function reverseWords(s) { return s.split(' ').reverse().join(' '); }\nfunction isPalindrome(s) {\n  var t = s.toLowerCase().split('').filter(function (c) { return c >= 'a' && c <= 'z'; }).join('');\n  return t === t.split('').reverse().join('');\n}\nfunction caesar(s, k) {\n  var out = '';\n  for (var i = 0; i < s.length; i++) {\n    var c = s.charCodeAt(i);\n    if (c >= 65 && c <= 90) out += String.fromCharCode((c - 65 + k) % 26 + 65);\n    else if (c >= 97 && c <= 122) out += String.fromCharCode((c - 97 + k) % 26 + 97);\n    else out += s[i];\n  }\n  return out;\n}\nfunction capitalize(s) {\n  return s.split(' ').map(function (w) { return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase(); }).join(' ');\n}\nfunction frequency(s) {\n  var f = {};\n  for (var i = 0; i < s.length; i++) f[s[i]] = (f[s[i]] || 0) + 1;\n  return Object.keys(f).sort().map(function (k) { return k + '=' + f[k]; }).join(',');\n}\nfunction vowels(s) { return s.split('').filter(function (c) { return 'aeiou'.indexOf(c.toLowerCase()) >= 0; }).length; }\n[\n  reverseWords('the quick brown fox'),\n  isPalindrome('A man, a plan, a canal: Panama'),\n  isPalindrome('not one'),\n  caesar('Hello, World!', 3),\n  caesar(caesar('Hello, World!', 3), 23),\n  capitalize('hELLO wORLD from kiteJS'),\n  frequency('mississippi'),\n  vowels('Programming Languages'),\n  'abc'.padStart(6, '-') + 'abc'.padEnd(6, '+'),\n  '  trim me  '.trim().length\n].join('|');\n",
            "fox brown quick the|true|false|Khoor, Zruog!|Hello, World!|Hello World From Kitejs|i=4,m=1,p=2,s=4|7|---abcabc+++|7",
        ),
        Program(
            "objects_and_prototypes",
            "function Animal(name) { this.name = name; }\nAnimal.prototype.speak = function () { return this.name + ' makes a sound'; };\nAnimal.prototype.kind = 'animal';\nfunction Dog(name) { Animal.call(this, name); }\nDog.prototype = Object.create(Animal.prototype);\nDog.prototype.constructor = Dog;\nDog.prototype.speak = function () { return Animal.prototype.speak.call(this) + ': woof'; };\nvar d = new Dog('Rex');\nvar base = { greet: function () { return 'hi ' + this.who; } };\nvar derived = Object.create(base, { who: { value: 'there', enumerable: true } });\nvar chain = [];\nfor (var o = d; o; o = Object.getPrototypeOf(o)) chain.push(o.constructor.name || '?');\nvar out = [\n  d.speak(),\n  d instanceof Dog, d instanceof Animal, d instanceof Object,\n  d.hasOwnProperty('name'), d.hasOwnProperty('speak'), 'speak' in d, 'kind' in d,\n  d.kind, Object.keys(d).join(), chain.join('>'),\n  derived.greet(), Object.getPrototypeOf(derived) === base,\n  Dog.prototype.isPrototypeOf(d), Animal.prototype.isPrototypeOf(d),\n  Object.getOwnPropertyNames(Dog.prototype).sort().join()\n];\nd.kind = 'pet';\nout.push(d.kind, Animal.prototype.kind, delete d.kind, d.kind);\nout.join('|');\n",
            "Rex makes a sound: woof|true|true|true|true|false|true|true|animal|name|Dog>Dog>Animal>Object|hi there|true|true|true|constructor,speak|pet|animal|true|animal",
        ),
        Program(
            "control_flow",
            "var out = [];\nouter: for (var i = 0; i < 4; i++) {\n  for (var j = 0; j < 4; j++) {\n    if (j === 2) continue outer;\n    if (i === 3) break outer;\n    out.push(i + '' + j);\n  }\n}\nfunction sw(x) {\n  var r = '';\n  switch (x) {\n    case 1: r += 'one';\n    case 2: r += 'two'; break;\n    case 'a': case 'b': r += 'ab'; break;\n    default: r += 'def';\n    case 3: r += 'three';\n  }\n  return r;\n}\nout.push(sw(1), sw(2), sw('a'), sw(9), sw(3));\nvar k = 0;\ndo { k += 3; } while (k < 10);\nout.push(k);\nvar w = 5, steps = '';\nwhile (w--) steps += w;\nout.push(steps);\nvar obj = { b: 1, a: 2, 10: 'x', 2: 'y' }, keys = '';\nfor (var key in obj) keys += key + ';';\nout.push(keys);\nvar s = '';\nfor (var ch of 'hey') s += ch.toUpperCase();\nout.push(s);\nvar x = (1, 2, 3);\nout.push(x, 5 > 3 ? 'yes' : 'no', 0 || 'or', 1 && 'and', null ?? 'nullish', 0 ?? 'zero');\nvar counter = 0;\nfunction tick() { return ++counter; }\nif (false && tick()) {}\nif (true || tick()) {}\nout.push(counter);\nblock: { out.push('in'); break block; out.push('never'); }\nout.join('|');\n",
            "00|01|10|11|20|21|onetwo|two|ab|defthree|three|12|43210|2;10;b;a;|HEY|3|yes|or|and|nullish|0|0|in",
        ),
        Program(
            "exceptions",
            "var log = [];\nfunction CustomError(message, code) {\n  this.name = 'CustomError';\n  this.message = message;\n  this.code = code;\n}\nCustomError.prototype = Object.create(Error.prototype);\nCustomError.prototype.constructor = CustomError;\nfunction ValidationError(field) {\n  var e = Error.call(this, 'bad ' + field);\n  this.message = e.message;\n  this.name = 'ValidationError';\n  this.field = field;\n}\nValidationError.prototype = Object.create(Error.prototype);\nValidationError.prototype.constructor = ValidationError;\nfunction order() {\n  try { log.push('try'); throw new Error('boom'); }\n  catch (e) { log.push('catch:' + e.message); return 'from catch'; }\n  finally { log.push('finally'); }\n}\nfunction override() { try { return 'try'; } finally { return 'finally'; } }\nfunction nested() {\n  try {\n    try { throw new CustomError('inner', 42); }\n    finally { log.push('inner finally'); }\n  } catch (e) { return e.name + ':' + e.code + ':' + (e instanceof Error) + ':' + (e instanceof CustomError); }\n}\nfunction rethrow() {\n  try { try { throw 'first'; } catch (e) { throw e + '+second'; } } catch (e) { return e; }\n}\nfunction loopFinally() {\n  var r = '';\n  for (var i = 0; i < 3; i++) { try { if (i === 1) continue; if (i === 2) break; r += i; } finally { r += 'f'; } }\n  return r;\n}\nvar out = [order(), log.join(), override(), nested(), rethrow(), loopFinally()];\ntry { throw new ValidationError('email'); } catch (e) { out.push(e.name, e.message, e.field, e instanceof ValidationError, e instanceof Error, '' + e); }\ntry { null.x; } catch (e) { out.push(e.name, e instanceof TypeError); }\ntry { undefinedFunction(); } catch (e) { out.push(e.name, e.message); }\ntry { throw { custom: true }; } catch (e) { out.push(typeof e, e.custom); }\ntry { throw 42; } catch (e) { out.push(e + 1); }\nvar caught = 0;\ntry { try { throw 1; } finally { caught++; } } catch (e) { caught += 10; }\nout.push(caught);\nout.push((function () { try { throw new RangeError('r'); } catch ({ name, message }) { return name + '/' + message; } })());\nvar err = new Error('with props', { cause: 'root' });\nout.push(err.cause, Object.keys(err).join(), err.propertyIsEnumerable('message'), JSON.stringify(err));\nout.join('|');\n",
            "from catch|try,catch:boom,finally|finally|CustomError:42:true:true|first+second|0fff|ValidationError|bad email|email|true|true|ValidationError: bad email|TypeError|true|ReferenceError|\"undefinedFunction\" is not defined.|object|true|43|11|RangeError/r|root||false|{}",
        ),
        Program(
            "higher_order_functions",
            "function compose() { var fns = Array.prototype.slice.call(arguments); return function (x) { return fns.reduceRight(function (acc, f) { return f(acc); }, x); }; }\nfunction pipe() { var fns = Array.prototype.slice.call(arguments); return function (x) { return fns.reduce(function (acc, f) { return f(acc); }, x); }; }\nfunction curry(fn) {\n  return function curried() {\n    var args = Array.prototype.slice.call(arguments);\n    if (args.length >= fn.length) return fn.apply(this, args);\n    return function () { return curried.apply(this, args.concat(Array.prototype.slice.call(arguments))); };\n  };\n}\nfunction memoize(fn) { var cache = {}, calls = 0; var m = function (x) { if (!(x in cache)) { calls++; cache[x] = fn(x); } return cache[x]; }; m.calls = function () { return calls; }; return m; }\nfunction partial(fn) { var preset = Array.prototype.slice.call(arguments, 1); return function () { return fn.apply(this, preset.concat(Array.prototype.slice.call(arguments))); }; }\nfunction debounceLike(fn) { var last; return function (x) { if (x === last) return 'skip'; last = x; return fn(x); }; }\nvar inc = function (x) { return x + 1; }, dbl = function (x) { return x * 2; }, sq = function (x) { return x * x; };\nvar add3 = curry(function (a, b, c) { return a + b + c; });\nvar slowSquare = memoize(function (x) { return x * x; });\nslowSquare(4); slowSquare(4); slowSquare(5);\nvar greet = partial(function (greeting, name, punct) { return greeting + ', ' + name + punct; }, 'Hello');\nvar d = debounceLike(function (x) { return 'ran:' + x; });\n[compose(inc, dbl)(5), pipe(inc, dbl)(5), compose(sq, inc, dbl)(2), add3(1)(2)(3), add3(1, 2)(3), add3(1)(2, 3), add3(1, 2, 3), slowSquare(4), slowSquare.calls(), greet('Kite', '!'), d(1), d(1), d(2),\n  [1, 2, 3, 4].map(sq).filter(function (x) { return x % 2; }).reduce(function (a, b) { return a + b; }), ['a', 'b'].map(function (c, i) { return c + i; }).join(), typeof compose()].join('|');\n",
            "11|12|25|6|6|6|6|16|2|Hello, Kite!|ran:1|skip|ran:2|10|a0,b1|function",
        ),
        Program(
            "linked_list",
            "function Node(value, next) { this.value = value; this.next = next || null; }\nfunction LinkedList() { this.head = null; this.size = 0; }\nLinkedList.prototype.push = function (v) {\n  var node = new Node(v);\n  if (!this.head) this.head = node;\n  else { var cur = this.head; while (cur.next) cur = cur.next; cur.next = node; }\n  this.size++;\n  return this;\n};\nLinkedList.prototype.toArray = function () { var out = []; for (var c = this.head; c; c = c.next) out.push(c.value); return out; };\nLinkedList.prototype.reverse = function () { var prev = null, cur = this.head; while (cur) { var next = cur.next; cur.next = prev; prev = cur; cur = next; } this.head = prev; return this; };\nLinkedList.prototype.remove = function (v) { if (!this.head) return false; if (this.head.value === v) { this.head = this.head.next; this.size--; return true; } for (var c = this.head; c.next; c = c.next) if (c.next.value === v) { c.next = c.next.next; this.size--; return true; } return false; };\nLinkedList.prototype.find = function (pred) { for (var c = this.head; c; c = c.next) if (pred(c.value)) return c.value; return undefined; };\nLinkedList.prototype.map = function (f) { var l = new LinkedList(); for (var c = this.head; c; c = c.next) l.push(f(c.value)); return l; };\nvar l = new LinkedList().push(1).push(2).push(3).push(4);\nvar out = [l.toArray().join(), l.size, l.reverse().toArray().join(), l.remove(3), l.remove(99), l.toArray().join(), l.size, l.find(function (v) { return v % 2 === 0; }), l.map(function (v) { return v * 10; }).toArray().join()];\nvar middle = (function (list) { var slow = list.head, fast = list.head; while (fast && fast.next) { slow = slow.next; fast = fast.next.next; } return slow.value; })(new LinkedList().push('a').push('b').push('c').push('d').push('e'));\nout.push(middle);\nout.join('|');\n",
            "1,2,3,4|4|4,3,2,1|true|false|4,2,1|3|4|40,20,10|c",
        ),
        Program(
            "binary_tree",
            "function TreeNode(v) { this.v = v; this.left = null; this.right = null; }\nfunction BST() { this.root = null; this.count = 0; }\nBST.prototype.insert = function (v) {\n  var node = new TreeNode(v);\n  this.count++;\n  if (!this.root) { this.root = node; return this; }\n  var cur = this.root;\n  while (true) {\n    if (v < cur.v) { if (!cur.left) { cur.left = node; break; } cur = cur.left; }\n    else { if (!cur.right) { cur.right = node; break; } cur = cur.right; }\n  }\n  return this;\n};\nBST.prototype.inorder = function (node, out) {\n  if (arguments.length === 0) { node = this.root; out = []; }\n  if (node) { this.inorder(node.left, out); out.push(node.v); this.inorder(node.right, out); }\n  return out;\n};\nBST.prototype.preorder = function (node = this.root, out = []) { if (node) { out.push(node.v); this.preorder(node.left, out); this.preorder(node.right, out); } return out; };\nBST.prototype.height = function (node = this.root) { return node ? 1 + Math.max(this.height(node.left), this.height(node.right)) : 0; };\nBST.prototype.contains = function (v) { var c = this.root; while (c) { if (v === c.v) return true; c = v < c.v ? c.left : c.right; } return false; };\nBST.prototype.min = function () { var c = this.root; while (c.left) c = c.left; return c.v; };\nBST.prototype.max = function () { var c = this.root; while (c.right) c = c.right; return c.v; };\nBST.prototype.levels = function () {\n  var out = [], q = this.root ? [this.root] : [];\n  while (q.length) {\n    var next = [], vals = [];\n    q.forEach(function (n) { vals.push(n.v); if (n.left) next.push(n.left); if (n.right) next.push(n.right); });\n    out.push(vals.join(','));\n    q = next;\n  }\n  return out.join(' / ');\n};\nvar t = new BST();\n[50, 30, 70, 20, 40, 60, 80, 35, 45, 65].forEach(function (v) { t.insert(v); });\n[t.inorder().join(), t.preorder().join(), t.height(), t.contains(45), t.contains(55), t.min(), t.max(), t.count, t.levels()].join('|');\n",
            "20,30,35,40,45,50,60,65,70,80|50,30,20,40,35,45,70,60,65,80|4|true|false|20|80|10|50 / 30,70 / 20,40,60,80 / 35,45,65",
        ),
        Program(
            "stack_queue",
            "function Stack() { this.items = []; }\nStack.prototype.push = function (x) { this.items.push(x); return this; };\nStack.prototype.pop = function () { return this.items.pop(); };\nStack.prototype.peek = function () { return this.items[this.items.length - 1]; };\nStack.prototype.isEmpty = function () { return this.items.length === 0; };\nfunction Queue() { this.items = []; }\nQueue.prototype.enqueue = function (x) { this.items.push(x); return this; };\nQueue.prototype.dequeue = function () { return this.items.shift(); };\nfunction balanced(s) {\n  var st = new Stack(), pairs = { ')': '(', ']': '[', '}': '{' };\n  for (var i = 0; i < s.length; i++) {\n    var c = s[i];\n    if ('([{'.indexOf(c) >= 0) st.push(c);\n    else if (c in pairs) { if (st.pop() !== pairs[c]) return false; }\n  }\n  return st.isEmpty();\n}\nfunction rpn(expr) {\n  var st = new Stack();\n  expr.split(' ').forEach(function (tok) {\n    if (!isNaN(tok)) st.push(Number(tok));\n    else { var b = st.pop(), a = st.pop(); st.push(tok === '+' ? a + b : tok === '-' ? a - b : tok === '*' ? a * b : a / b); }\n  });\n  return st.pop();\n}\nvar q = new Queue().enqueue('a').enqueue('b').enqueue('c');\nvar order = [q.dequeue(), q.dequeue(), q.enqueue('d').dequeue(), q.dequeue(), q.dequeue()].join();\n[balanced('([]{})'), balanced('([)]'), balanced('(('), balanced(''), rpn('3 4 + 2 *'), rpn('5 1 2 + 4 * + 3 -'), order, new Stack().push(1).push(2).peek()].join('|');\n",
            "true|false|false|true|14|14|a,b,c,d,|2",
        ),
        Program(
            "prime_sieve",
            "function sieve(n) {\n  var flags = new Array(n + 1).fill(true), primes = [];\n  flags[0] = flags[1] = false;\n  for (var i = 2; i <= n; i++) {\n    if (!flags[i]) continue;\n    primes.push(i);\n    for (var j = i * i; j <= n; j += i) flags[j] = false;\n  }\n  return primes;\n}\nfunction fizzbuzz(n) {\n  var out = [];\n  for (var i = 1; i <= n; i++) out.push(i % 15 === 0 ? 'FizzBuzz' : i % 3 === 0 ? 'Fizz' : i % 5 === 0 ? 'Buzz' : String(i));\n  return out;\n}\nfunction collatz(n) { var steps = 0; while (n !== 1) { n = n % 2 ? 3 * n + 1 : n / 2; steps++; } return steps; }\nfunction isPerfect(n) { var s = 0; for (var i = 1; i < n; i++) if (n % i === 0) s += i; return s === n; }\nfunction digitsReversed(n) { return Number(String(n).split('').reverse().join('')); }\nvar perfect = [];\nfor (var i = 2; i < 10000; i++) if (isPerfect(i)) perfect.push(i);\n[sieve(100).join(), sieve(100).length, fizzbuzz(15).join(), collatz(27), collatz(97), perfect.join(), digitsReversed(12345), sieve(2).join(), sieve(1).length].join('|');\n",
            "2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97|25|1,2,Fizz,4,Buzz,Fizz,7,8,Fizz,Buzz,11,Fizz,13,14,FizzBuzz|111|118|6,28,496,8128|54321|2|0",
        ),
        Program(
            "deep_equal",
            "function deepEqual(a, b) {\n  if (a === b) return true;\n  if (typeof a !== typeof b) return false;\n  if (typeof a === 'number' && isNaN(a) && isNaN(b)) return true;\n  if (a === null || b === null || typeof a !== 'object') return false;\n  if (Array.isArray(a) !== Array.isArray(b)) return false;\n  var ka = Object.keys(a), kb = Object.keys(b);\n  if (ka.length !== kb.length) return false;\n  return ka.every(function (k) { return kb.indexOf(k) >= 0 && deepEqual(a[k], b[k]); });\n}\nvar cases = [\n  [1, 1], [1, '1'], [NaN, NaN], [null, undefined], [null, null], [[1, 2], [1, 2]], [[1, 2], [2, 1]], [{ a: 1, b: [1, { c: 2 }] }, { b: [1, { c: 2 }], a: 1 }],\n  [{ a: 1 }, { a: 1, b: undefined }], [[], {}], [{ a: [] }, { a: {} }], ['x', 'x'], [function () {}, function () {}], [{ a: { b: { c: 1 } } }, { a: { b: { c: 2 } } }]\n];\ncases.map(function (c) { return deepEqual(c[0], c[1]) ? 1 : 0; }).join('');\n",
            "10101101000100",
        ),
        Program(
            "coercion_matrix",
            "var values = [0, 1, -1, '', '0', '1', 'a', ' ', true, false, null, undefined, NaN, [], [0], [1], [1, 2], {}, Infinity];\nfunction show(v) {\n  if (v === undefined) return 'undefined';\n  if (v === null) return 'null';\n  if (typeof v === 'string') return JSON.stringify(v);\n  if (Array.isArray(v)) return '[' + v.join(',') + ']';\n  if (typeof v === 'object') return '{}';\n  return String(v);\n}\nvar rows = [];\nfor (var i = 0; i < values.length; i++) {\n  var row = show(values[i]) + ':';\n  for (var j = 0; j < values.length; j++) row += (values[i] == values[j] ? '1' : '0');\n  rows.push(row);\n}\nvar plus = values.map(function (v) { return show(v + 1); }).join(',');\nvar minus = values.map(function (v) { return show(v - 1); }).join(',');\nvar bool = values.map(function (v) { return !!v ? 't' : 'f'; }).join('');\nvar types = values.map(function (v) { return typeof v; }).join(',');\nvar nums = values.map(function (v) { return show(Number(v)); }).join(',');\nvar strs = values.map(function (v) { return String(v); }).join('|');\n[rows.join('\\n'), plus, minus, bool, types, nums, strs, null < 1, undefined < 1, NaN == NaN, [1] == 1, [1, 2] == '1,2', {} + '', '' + {}, [] + [], [] + {}, 1 + '2' - 1, '3' * '4', true + true, [] == ![], null == false, undefined == null].join('\\n');\n",
            "0:1001100101000110000\n1:0100010010000001000\n-1:0010000000000000000\n\"\":1001000001000100000\n\"0\":1000100001000010000\n\"1\":0100010010000001000\n\"a\":0000001000000000000\n\" \":1000000101000000000\ntrue:0100010010000001000\nfalse:1001100101000110000\nnull:0000000000110000000\nundefined:0000000000110000000\nNaN:0000000000000000000\n[]:1001000001000100000\n[0]:1000100001000010000\n[1]:0100010010000001000\n[1,2]:0000000000000000100\n{}:0000000000000000010\nInfinity:0000000000000000001\n1,2,0,\"1\",\"01\",\"11\",\"a1\",\" 1\",2,1,1,NaN,NaN,\"1\",\"01\",\"11\",\"1,21\",\"[object Object]1\",Infinity\n-1,0,-2,-1,-1,0,NaN,-1,0,-1,-1,NaN,NaN,-1,-1,0,NaN,NaN,Infinity\nfttftttttfffftttttt\nnumber,number,number,string,string,string,string,string,boolean,boolean,object,undefined,number,object,object,object,object,object,number\n0,1,-1,0,0,1,NaN,0,1,0,0,NaN,NaN,0,0,1,NaN,NaN,Infinity\n0|1|-1||0|1|a| |true|false|null|undefined|NaN||0|1|1,2|[object Object]|Infinity\ntrue\nfalse\nfalse\ntrue\ntrue\n[object Object]\n[object Object]\n\n[object Object]\n11\n12\n2\ntrue\nfalse\ntrue",
        ),
        Program(
            "array_holes_and_length",
            "var a = [1, , 3];\nvar out = [a.length, 1 in a, a[1], a.hasOwnProperty(1), a.indexOf(undefined), a.includes(undefined), a.join('-'), String(a)];\nvar visited = [];\na.forEach(function (v, i) { visited.push(i); });\nout.push(visited.join(), a.map(function (x) { return x * 2; }).length, a.filter(function () { return true; }).length, Object.keys(a).join());\nvar b = [1, 2, 3, 4, 5];\nb.length = 2;\nout.push(b.join(), b[3]);\nb.length = 4;\nout.push(b.length, b.join('-'), 3 in b);\nb[10] = 'far';\nout.push(b.length, Object.keys(b).join());\ndelete b[0];\nout.push(b.length, 0 in b, b.join('|'));\nvar c = new Array(3);\nout.push(c.length, c.join('x'), c.fill(0).join(), Array(3).fill().map(function (_, i) { return i; }).join(), [, ,].length, [1, 2, ,].length);\nvar d = [];\nd[2] = 'c';\nd.unshift('a');\nout.push(d.length, d.join(), d.shift(), d.length, d.pop(), d.length);\nout.push([NaN].indexOf(NaN), [NaN].includes(NaN), [1, 2, 3].indexOf('2'), [1, 2, 3].lastIndexOf(3, -2), [0].includes(-0), [-0].indexOf(0));\nvar sparse = [];\nsparse[4294967294] = 'max';\nout.push(sparse.length);\ntry { sparse.length = 4294967296; } catch (e) { out.push(e.name); }\nout.join('|');\n",
            "3|false||false|-1|true|1--3|1,,3|0,2|3|2|0,2|1,2||4|1-2--|false|11|0,1,10|11|false||2|||||||||far|3|xx|0,0,0|0,1,2|2|3|4|a,,,c|a|3|c|2|-1|true|-1|-1|true|0|4294967295|RangeError",
        ),
        Program(
            "json_roundtrip",
            "var data = {\n  name: 'Kite', version: 1.5, tags: ['js', 'kmp'], nested: { deep: { deeper: [1, { x: null }] } },\n  empty: {}, emptyArr: [], flag: true, nothing: null, skipped: undefined, fn: function () {},\n  unicode: 'café 😀', ctrl: 'a\\tb\\nc\"d\\\\e'\n};\nvar text = JSON.stringify(data);\nvar back = JSON.parse(text);\nvar same = JSON.stringify(back) === text;\nvar pretty = JSON.stringify({ a: [1, { b: 2 }], c: 'x' }, null, 2);\nvar tabbed = JSON.stringify({ a: [1] }, null, '\\t');\nvar filtered = JSON.stringify(data, ['name', 'tags', 'version']);\nvar replaced = JSON.stringify(data, function (k, v) { return typeof v === 'number' ? v * 2 : v; });\nvar revived = JSON.parse('{\"n\":1,\"o\":{\"n\":2},\"a\":[{\"n\":3}]}', function (k, v) { return k === 'n' ? v * 10 : v; });\nvar dropped = JSON.parse('{\"keep\":1,\"drop\":2}', function (k, v) { return k === 'drop' ? undefined : v; });\nvar custom = JSON.stringify({ when: { toJSON: function (key) { return 'json:' + key; } }, list: [{ toJSON: function () { return 1; } }] });\nvar edge = JSON.stringify([NaN, Infinity, -0, 1e21, new Number(2), new String('s'), new Boolean(false), undefined, function () {}]);\nvar order = JSON.stringify({ b: 1, a: 2, 2: 'two', 1: 'one' });\nvar errors = [];\n['{', '[1,]', \"{'a':1}\", '01', 'undefined', '{\"a\":1,}', '\"\\\\x41\"', '', ' '].forEach(function (s) { try { JSON.parse(s); errors.push('ok'); } catch (e) { errors.push(e.name); } });\nvar cyc = {}; cyc.self = cyc;\ntry { JSON.stringify(cyc); } catch (e) { errors.push(e.name); }\n[text, same, pretty, tabbed, filtered, replaced, JSON.stringify(revived), JSON.stringify(dropped), custom, edge, order, errors.join(), typeof back.nested.deep.deeper[1].x, back.unicode.length, Object.keys(back).join()].join('\\n');\n",
            "{\"name\":\"Kite\",\"version\":1.5,\"tags\":[\"js\",\"kmp\"],\"nested\":{\"deep\":{\"deeper\":[1,{\"x\":null}]}},\"empty\":{},\"emptyArr\":[],\"flag\":true,\"nothing\":null,\"unicode\":\"café 😀\",\"ctrl\":\"a\\tb\\nc\\\"d\\\\e\"}\ntrue\n{\n  \"a\": [\n    1,\n    {\n      \"b\": 2\n    }\n  ],\n  \"c\": \"x\"\n}\n{\n\t\"a\": [\n\t\t1\n\t]\n}\n{\"name\":\"Kite\",\"tags\":[\"js\",\"kmp\"],\"version\":1.5}\n{\"name\":\"Kite\",\"version\":3,\"tags\":[\"js\",\"kmp\"],\"nested\":{\"deep\":{\"deeper\":[2,{\"x\":null}]}},\"empty\":{},\"emptyArr\":[],\"flag\":true,\"nothing\":null,\"unicode\":\"café 😀\",\"ctrl\":\"a\\tb\\nc\\\"d\\\\e\"}\n{\"n\":10,\"o\":{\"n\":20},\"a\":[{\"n\":30}]}\n{\"keep\":1}\n{\"when\":\"json:when\",\"list\":[1]}\n[null,null,0,1e+21,2,\"s\",false,null,null]\n{\"1\":\"one\",\"2\":\"two\",\"b\":1,\"a\":2}\nSyntaxError,SyntaxError,SyntaxError,SyntaxError,SyntaxError,SyntaxError,SyntaxError,SyntaxError,SyntaxError,TypeError\nobject\n7\nname,version,tags,nested,empty,emptyArr,flag,nothing,unicode,ctrl",
        ),
        Program(
            "getters_setters_defineproperty",
            "var temp = { _c: 25, get f() { return this._c * 9 / 5 + 32; }, set f(v) { this._c = (v - 32) * 5 / 9; } };\ntemp.f = 212;\nvar o = {};\nObject.defineProperty(o, 'ro', { value: 1, writable: false, enumerable: true, configurable: false });\nObject.defineProperty(o, 'hidden', { value: 2, enumerable: false });\nObject.defineProperty(o, 'acc', { get: function () { return 'got'; }, enumerable: true, configurable: true });\nObject.defineProperties(o, { p: { value: 'p', enumerable: true }, q: { value: 'q' } });\no.ro = 99;\ndelete o.ro;\nvar d = Object.getOwnPropertyDescriptor(o, 'ro');\nvar out = [temp._c, temp.f, Object.keys(temp).join(), o.ro, o.hidden, o.acc, Object.keys(o).join(), Object.getOwnPropertyNames(o).join(), JSON.stringify(d), JSON.stringify(Object.getOwnPropertyDescriptor(o, 'acc').get === undefined)];\nvar errors = [];\n(function () {\n  'use strict';\n  try { o.ro = 5; } catch (e) { errors.push(e.name); }\n  try { delete o.ro; } catch (e) { errors.push(e.name); }\n  try { o.acc = 1; } catch (e) { errors.push(e.name); }\n  try { Object.defineProperty(o, 'ro', { value: 3 }); } catch (e) { errors.push(e.name); }\n  var frozen = Object.freeze({ a: 1 });\n  try { frozen.a = 2; } catch (e) { errors.push(e.name); }\n  try { frozen.b = 2; } catch (e) { errors.push(e.name); }\n  var sealed = Object.seal({ a: 1 });\n  sealed.a = 2;\n  try { sealed.b = 1; } catch (e) { errors.push(e.name); }\n  errors.push(sealed.a);\n})();\nout.push(errors.join());\nvar counter = { count: 0 };\nObject.defineProperty(counter, 'next', { get: function () { return ++this.count; } });\nout.push(counter.next, counter.next, counter.count, JSON.stringify(counter));\nout.join('|');\n",
            "100|212|_c,f|1|2|got|ro,acc,p|ro,hidden,acc,p,q|{\"value\":1,\"writable\":false,\"enumerable\":true,\"configurable\":false}|false|TypeError,TypeError,TypeError,TypeError,TypeError,TypeError,TypeError,2|1|2|2|{\"count\":2}",
        ),
        Program(
            "error_messages",
            "var attempts = [\n  function () { return null.prop; },\n  function () { return undefined.prop; },\n  function () { var o = {}; return o.missing.deeper; },\n  function () { var o = {}; return o.notAFunction(); },\n  function () { return notDefinedAnywhere; },\n  function () { notDefinedAnywhere = 1; },\n  function () { 'use strict'; notDefinedStrict = 1; },\n  function () { return new Array(-1); },\n  function () { return [].length = -1; },\n  function () { return (1).toFixed(200); },\n  function () { return 'abc'.repeat(-1); },\n  function () { return new (function () {})().x.y; },\n  function () { return JSON.parse('{bad'); },\n  function () { const c = 1; c = 2; },\n  function () { return Object.defineProperty(1, 'x', {}); },\n  function () { var o = Object.freeze({}); 'use strict'; o.x = 1; return o.x; },\n  function () { 'use strict'; var o = Object.freeze({}); o.x = 1; },\n  function () { return decodeURIComponent('%'); },\n  function () { throw new TypeError('custom type'); },\n  function () { return [1, 2].reduce(function () {}, undefined) + [].reduce(function () {}); },\n  function () { return new 5.5; },\n  function () { return 1 in 1; },\n  function () { return {} instanceof 1; },\n  function () { return Object.create(5); },\n  function () { return 'x'.charAt.call(null); },\n  function () { return Array.prototype.join.call(undefined); }\n];\nattempts.map(function (f, i) {\n  try { var r = f(); return i + ':ok:' + r; }\n  catch (e) { return i + ':' + (e && e.name) + ':' + (e && e.message); }\n}).join('\\n');\n",
            "0:TypeError:Cannot read property \"prop\" from null\n1:TypeError:Cannot read property \"prop\" from undefined\n2:TypeError:Cannot read property \"deeper\" from undefined\n3:TypeError:Cannot find function notAFunction.\n4:ReferenceError:\"notDefinedAnywhere\" is not defined.\n5:ok:undefined\n6:ReferenceError:Assignment to undefined \"notDefinedStrict\" in strict mode\n7:RangeError:Inappropriate array length.\n8:RangeError:Inappropriate array length.\n9:RangeError:Precision 200 out of range.\n10:RangeError:Invalid count value\n11:TypeError:Cannot read property \"y\" from undefined\n12:SyntaxError:Unexpected token in object literal\n13:ok:undefined\n14:TypeError:Expected argument of type object, but instead had type number\n15:ok:undefined\n16:TypeError:Cannot add properties to this object because extensible is false.\n17:URIError:Malformed URI sequence.\n18:TypeError:custom type\n19:TypeError:Reduce of empty array with no initial value\n20:TypeError:5.5 is not a function, it is number.\n21:TypeError:Can't use 'in' on a non-object.\n22:TypeError:Can't use 'instanceof' on a non-object.\n23:TypeError:Expected argument of type object, but instead had type number\n24:TypeError:String.prototype.charAt method called on null or undefined\n25:TypeError:Cannot convert undefined to an object.",
        ),
        Program(
            "wrapper_objects",
            "var n = new Number(5), s = new String('str'), b = new Boolean(false);\nvar prim = 5;\nprim.prop = 'lost';\nvar out = [typeof n, typeof s, typeof b, n + 1, s + '!', b ? 'truthy' : 'falsy', n == 5, n === 5, s == 'str', s === 'str', b == false, b === false, !b, !!b,\n  n.valueOf() === 5, s.valueOf() === 'str', b.valueOf() === false, n instanceof Number, (5) instanceof Number, Object(5) instanceof Number, typeof Object('x'), Object(true).valueOf(),\n  prim.prop, s.length, s[0], s.charAt(1), Object.keys(s).join(), JSON.stringify([n, s, b]), n.toFixed(1), new Number(1) + new Number(2), new String('a') + new String('b'), new Boolean(false) + 1,\n  Number(new Number(3)) === 3, String(new String('x')) === 'x', new Number(NaN) == NaN, [new Number(1)].indexOf(1), [1].indexOf(new Number(1)), new String('ab') == new String('ab'), Object.prototype.toString.call(n), Object.prototype.toString.call(s), Object.prototype.toString.call(b),\n  (function () { 'use strict'; return typeof this; }).call(5), (function () { return typeof this; }).call(5), (function () { return this instanceof Number; }).call(5)];\nout.join('|');\n",
            "object|object|object|6|str!|truthy|true|false|true|false|true|false|false|true|true|true|true|true|false|true|object|true||3|s|t|0,1,2|[5,\"str\",false]|5.0|3|ab|1|true|true|false|-1|-1|false|[object Number]|[object String]|[object Boolean]|object|object|true",
        ),
        Program(
            "optional_chaining_nullish",
            "var data = { user: { name: 'k', tags: ['a'], greet: function () { return 'hi ' + this.name; }, zero: 0, empty: '', f: false }, list: null };\nvar out = [\n  data.user?.name, data.missing?.name, data.list?.[0], data.user?.tags?.[0], data.user?.tags?.[5], data.user.greet?.(), data.user.nope?.(), data?.user?.['name'],\n  data.user.zero ?? 'default', data.user.empty ?? 'default', data.user.f ?? 'default', data.user.undef ?? 'default', data.list ?? 'default', null ?? undefined ?? 'last',\n  data.user.zero || 'fallback', data.user.empty || 'fallback', (data.user.zero ?? 5) + 1, data.missing?.deep.deeper.deepest, typeof data.missing?.(),\n  (null)?.x, (undefined)?.[1], data.user?.tags.length, data.user.greet?.call({ name: 'other' })\n];\nvar count = 0;\nfunction side() { count++; return { v: 1 }; }\nvar r = null?.[side()];\nout.push(count, r, side()?.v, count);\nout.push(typeof data.user?.greet, delete data.user?.zero, 'zero' in data.user);\nout.join('|');\n",
            "k|||a||hi k||k|0||false|default|default|last|fallback|fallback|1||undefined|||1|hi other|0||1|1|function|true|false",
        ),
        Program(
            "lazy_pipeline",
            "// A pull-based pipeline: nothing runs until the consumer asks for the next value.\nfunction* range(start, end, step) {\n  for (var i = start; i < end; i += (step || 1)) yield i;\n}\nfunction* map(it, f) {\n  for (var v of it) yield f(v);\n}\nfunction* filter(it, pred) {\n  for (var v of it) if (pred(v)) yield v;\n}\nfunction* take(it, n) {\n  var i = 0;\n  for (var v of it) {\n    if (i++ >= n) return;\n    yield v;\n  }\n}\nfunction* zip(a, b) {\n  var ia = a[Symbol.iterator]();\n  var ib = b[Symbol.iterator]();\n  while (true) {\n    var ra = ia.next();\n    var rb = ib.next();\n    if (ra.done || rb.done) return;\n    yield [ra.value, rb.value];\n  }\n}\nfunction drain(it) {\n  var out = [];\n  for (var v of it) out.push(v);\n  return out;\n}\n\nvar calls = 0;\nfunction counted(x) { calls++; return x * x; }\n\nvar squares = take(map(range(1, 1000), counted), 5);\nvar first = drain(squares).join();\nvar lazily = calls;\n\nvar evens = drain(take(filter(range(0, 100), function (n) { return n % 2 === 0; }), 6)).join();\nvar pairs = drain(zip(range(0, 4), 'abcd')).map(function (p) { return p.join(':'); }).join();\nvar spread = [...take(range(10, 100, 10), 4)].join();\nvar summed = drain(map(range(1, 6), function (n) { return n; })).reduce(function (a, b) { return a + b; }, 0);\n\n// Rhino does not close a generator when a for-of loop breaks, so this finally never runs.\n// The value stays at its starting point, which is what both engines have to agree on.\nvar closedAt = -1;\nfunction* watched() {\n  try {\n    var i = 0;\n    while (true) yield i++;\n  } finally {\n    closedAt = i;\n  }\n}\nfor (var v of watched()) if (v === 3) break;\n\n// Delegation keeps the same laziness.\nfunction* concat(a, b) { yield* a; yield* b; }\nvar joined = drain(concat(range(0, 3), range(10, 13))).join();\n\n[first, lazily, evens, pairs, spread, summed, closedAt, joined].join('|');\n",
            "1,4,9,16,25|6|0,2,4,6,8,10|0:a,1:b,2:c,3:d|10,20,30,40|15|-1|0,1,2,10,11,12",
        ),
        Program(
            "tree_walker",
            "// An in-order walk written as a generator, plus the same walk done eagerly for comparison.\nfunction Node(value, left, right) {\n  this.value = value;\n  this.left = left || null;\n  this.right = right || null;\n}\nfunction insert(node, value) {\n  if (node === null) return new Node(value);\n  if (value < node.value) node.left = insert(node.left, value);\n  else if (value > node.value) node.right = insert(node.right, value);\n  return node;\n}\nvar root = null;\nvar input = [50, 30, 70, 20, 40, 60, 80, 35, 45, 75];\nfor (var i = 0; i < input.length; i++) root = insert(root, input[i]);\n\nfunction* inOrder(node) {\n  if (node === null) return;\n  yield* inOrder(node.left);\n  yield node.value;\n  yield* inOrder(node.right);\n}\nfunction* preOrder(node) {\n  if (node === null) return;\n  yield node.value;\n  yield* preOrder(node.left);\n  yield* preOrder(node.right);\n}\nfunction* leaves(node) {\n  if (node === null) return;\n  if (node.left === null && node.right === null) { yield node.value; return; }\n  yield* leaves(node.left);\n  yield* leaves(node.right);\n}\n\nvar sortedOut = [...inOrder(root)].join();\nvar pre = [...preOrder(root)].join();\nvar leafList = [...leaves(root)].join();\n\n// The generator is lazy: stop as soon as the answer is known.\nfunction firstAbove(node, limit) {\n  for (var v of inOrder(node)) if (v > limit) return v;\n  return null;\n}\nvar above = firstAbove(root, 44);\n\n// Depth without a generator, to check the tree itself.\nfunction depth(node) {\n  if (node === null) return 0;\n  var l = depth(node.left);\n  var r = depth(node.right);\n  return 1 + (l > r ? l : r);\n}\n\n// A generator can be restarted only by calling the function again.\nvar it = inOrder(root);\nvar firstThree = [it.next().value, it.next().value, it.next().value].join();\nit.return(0);\nvar afterReturn = it.next().done;\n\n[sortedOut, pre, leafList, above, depth(root), firstThree, afterReturn].join('|');\n",
            "20,30,35,40,45,50,60,70,75,80|50,30,20,40,35,45,70,60,80,75|20,35,45,60,75|45|4|20,30,35|true",
        ),
        Program(
            "fibonacci_generator",
            "// Several ways to produce the same sequence, so the generator can be checked against them.\nfunction* fib() {\n  var a = 0, b = 1;\n  while (true) {\n    yield a;\n    var next = a + b;\n    a = b;\n    b = next;\n  }\n}\nfunction fibArray(n) {\n  var out = [0, 1];\n  while (out.length < n) out.push(out[out.length - 1] + out[out.length - 2]);\n  return out.slice(0, n);\n}\nfunction fibRecursive(n) {\n  return n < 2 ? n : fibRecursive(n - 1) + fibRecursive(n - 2);\n}\n\nfunction takeN(it, n) {\n  var out = [];\n  for (var v of it) {\n    if (out.length >= n) break;\n    out.push(v);\n  }\n  return out;\n}\n\nvar fromGenerator = takeN(fib(), 15);\nvar fromArray = fibArray(15);\nvar same = fromGenerator.join() === fromArray.join();\nvar recursiveMatch = fromGenerator.slice(0, 12).every(function (v, i) { return v === fibRecursive(i); });\n\n// Two iterators over the same generator function are independent.\nvar a = fib();\nvar b = fib();\na.next(); a.next(); a.next();\nvar independent = a.next().value + ':' + b.next().value;\n\n// Sending a value in restarts the sequence.\nfunction* resettable() {\n  var a = 0, b = 1;\n  while (true) {\n    var reset = yield a;\n    if (reset !== undefined) { a = reset; b = 1; continue; }\n    var next = a + b;\n    a = b;\n    b = next;\n  }\n}\nvar r = resettable();\nvar before = [r.next().value, r.next().value, r.next().value, r.next().value].join();\nvar afterReset = r.next(100).value;\nvar thenOn = [r.next().value, r.next().value].join();\n\n// Big values stay exact until doubles run out of integer precision.\nvar big = takeN(fib(), 79);\nvar last = big[big.length - 1];\nvar exact = last === 14472334024676221;\n\n[fromGenerator.join(), same, recursiveMatch, independent, before, afterReset, thenOn, big.length, last, exact].join('|');\n",
            "0,1,1,2,3,5,8,13,21,34,55,89,144,233,377|true|true|2:0|0,1,1,2|100|1,101|79|8944394323791464|false",
        ),
        Program(
            "regex_tokenizer",
            "// A tokenizer built from one sticky pattern per token kind.\nvar SPEC = [\n  ['ws', /\\s+/y],\n  ['number', /\\d+(?:\\.\\d+)?/y],\n  ['string', /\"(?:[^\"\\\\]|\\\\.)*\"/y],\n  ['ident', /[A-Za-z_\$][A-Za-z0-9_\$]*/y],\n  ['op', /[+\\-*\\/=<>!]=?|&&|\\|\\||[(){};,]/y]\n];\nfunction tokenize(src) {\n  var out = [], pos = 0;\n  outer: while (pos < src.length) {\n    for (var i = 0; i < SPEC.length; i++) {\n      var name = SPEC[i][0], re = SPEC[i][1];\n      re.lastIndex = pos;\n      var m = re.exec(src);\n      if (m && m.index === pos) {\n        if (name !== 'ws') out.push(name + ':' + m[0]);\n        pos = re.lastIndex;\n        continue outer;\n      }\n    }\n    out.push('bad:' + src.charAt(pos));\n    pos++;\n  }\n  return out;\n}\nvar tokens = tokenize('var x1 = 3.5 + count(a, \"he\\\\\"llo\") && b <= 10;');\n\n// The same source split a second way, to cross-check the count.\nvar byGlobal = 'var x1 = 3.5 + count(a, \"he\\\\\"llo\") && b <= 10;'.match(/[A-Za-z_\$][A-Za-z0-9_\$]*/g);\n\n// A tiny expression evaluator over the token stream.\nfunction sumNumbers(src) {\n  var total = 0, re = /\\d+(?:\\.\\d+)?/g, m;\n  while ((m = re.exec(src)) !== null) total += Number(m[0]);\n  return total;\n}\n\n// Named groups pulled out of a key=value list.\nvar pairs = [];\nvar kv = /(?<key>\\w+)=(?<value>[^;]+)/g, hit;\nwhile ((hit = kv.exec('a=1;bb=two;ccc=3 3')) !== null) pairs.push(hit.groups.key + '->' + hit.groups.value);\n\n[tokens.join(' '), tokens.length, byGlobal.join(), sumNumbers('a1 b22 c3.5'), pairs.join(' ')].join('|');\n",
            "ident:var ident:x1 op:= number:3.5 op:+ ident:count op:( ident:a op:, string:\"he\\\"llo\" op:) op:&& ident:b op:<= number:10 op:;|16|var,x1,count,a,he,llo,b|26.5|a->1 bb->two ccc->3 3",
        ),
        Program(
            "regex_template_engine",
            "// A small template engine: {{name}}, {{#each}}...{{/each}} and {{!comment}}.\nfunction render(tpl, data) {\n  return tpl\n    .replace(/\\{\\{!.*?\\}\\}/g, '')\n    .replace(/\\{\\{#each (\\w+)\\}\\}([\\s\\S]*?)\\{\\{\\/each\\}\\}/g, function (all, key, body) {\n      var list = data[key] || [];\n      var out = '';\n      for (var i = 0; i < list.length; i++) {\n        out += body.replace(/\\{\\{this\\}\\}/g, String(list[i])).replace(/\\{\\{@index\\}\\}/g, String(i));\n      }\n      return out;\n    })\n    .replace(/\\{\\{(\\w+(?:\\.\\w+)*)\\}\\}/g, function (all, path) {\n      var parts = path.split('.'), value = data;\n      for (var i = 0; i < parts.length; i++) {\n        if (value === undefined || value === null) return '';\n        value = value[parts[i]];\n      }\n      return value === undefined ? '' : String(value);\n    });\n}\nvar data = { title: 'Report', user: { name: 'Ann' }, items: ['a', 'b', 'c'], missing: undefined };\nvar tpl = '{{!ignored}}<h1>{{title}}</h1> by {{user.name}} ({{user.email}}) {{#each items}}[{{@index}}:{{this}}]{{/each}} {{nope}}!';\nvar out = render(tpl, data);\n\n// Escaping with a replacement string rather than a function.\nvar escaped = '<a href=\"x\">&</a>'.replace(/[<>&\"]/g, function (c) {\n  return { '<': '&lt;', '>': '&gt;', '&': '&amp;', '\"': '&quot;' }[c];\n});\n\n// \$-patterns in a plain replacement string.\nvar swapped = 'first last'.replace(/(\\w+) (\\w+)/, '\$2, \$1');\nvar doubled = 'abc'.replace(/b/, '\$&\$&');\nvar around = 'abc'.replace(/b/, \"[\$`|\$']\");\n\n[out, escaped, swapped, doubled, around].join('|');\n",
            "<h1>Report</h1> by Ann () [0:a][1:b][2:c] !|&lt;a href=&quot;x&quot;&gt;&amp;&lt;/a&gt;|last, first|abbc|a[a|c]c",
        ),
        Program(
            "regex_csv_parser",
            "// A CSV reader that handles quoted fields, embedded commas, quotes and newlines.\nfunction parseCSV(text) {\n  var rows = [], row = [], field = '', i = 0, inQuotes = false;\n  while (i < text.length) {\n    var c = text.charAt(i);\n    if (inQuotes) {\n      if (c === '\"') {\n        if (text.charAt(i + 1) === '\"') { field += '\"'; i += 2; continue; }\n        inQuotes = false; i++; continue;\n      }\n      field += c; i++; continue;\n    }\n    if (c === '\"') { inQuotes = true; i++; continue; }\n    if (c === ',') { row.push(field); field = ''; i++; continue; }\n    if (c === '\\n') { row.push(field); rows.push(row); row = []; field = ''; i++; continue; }\n    field += c; i++;\n  }\n  row.push(field);\n  rows.push(row);\n  return rows;\n}\nvar text = 'name,age,note\\n\"Doe, Jane\",31,\"said \"\"hi\"\"\"\\nBob,25,plain\\n\"multi\\nline\",1,x';\nvar rows = parseCSV(text);\n\n// The same job done with a single regex, to compare on the simple rows.\nvar simpleRe = /(?:^|,)(?:\"([^\"]*)\"|([^\",]*))/g;\nfunction parseSimpleRow(line) {\n  var out = [], m;\n  simpleRe.lastIndex = 0;\n  while ((m = simpleRe.exec(line)) !== null) {\n    out.push(m[1] !== undefined ? m[1] : m[2]);\n    if (simpleRe.lastIndex === line.length) break;\n  }\n  return out;\n}\nvar simple = parseSimpleRow('a,b,\"c,d\",e');\n\n// Splitting on a pattern that keeps its delimiter.\nvar kept = 'a1b22c333d'.split(/(\\d+)/);\n\n[rows.length, rows[1].join('|'), rows[3].join('|'), simple.join('|'), kept.join('~'), JSON.stringify(rows[0])].join('#');\n",
            "4#Doe, Jane|31|said \"hi\"#multi\nline|1|x#a|b|c,d|e#a~1~b~22~c~333~d#[\"name\",\"age\",\"note\"]",
        ),
        Program(
            "regex_log_parser",
            "// Parses a small access log and rolls it up.\nvar LINE = /^(?<ip>\\d+\\.\\d+\\.\\d+\\.\\d+) - (?<user>\\S+) \\[(?<when>[^\\]]+)\\] \"(?<method>[A-Z]+) (?<path>\\S+) HTTP\\/(?<ver>[\\d.]+)\" (?<status>\\d{3}) (?<bytes>\\d+|-)\$/;\nvar lines = [\n  '10.0.0.1 - alice [2024-01-02T03:04:05] \"GET /index.html HTTP/1.1\" 200 1234',\n  '10.0.0.2 - - [2024-01-02T03:04:06] \"POST /api/items HTTP/1.1\" 201 87',\n  'garbage line',\n  '10.0.0.1 - alice [2024-01-02T03:04:07] \"GET /missing HTTP/1.0\" 404 -',\n  '10.0.0.3 - bob [2024-01-02T03:04:08] \"DELETE /api/items/7 HTTP/1.1\" 500 0'\n];\nvar parsed = [], bad = 0;\nfor (var i = 0; i < lines.length; i++) {\n  var m = LINE.exec(lines[i]);\n  if (m === null) { bad++; continue; }\n  parsed.push(m.groups);\n}\nvar byStatus = {};\nfor (var j = 0; j < parsed.length; j++) {\n  var s = parsed[j].status.charAt(0) + 'xx';\n  byStatus[s] = (byStatus[s] || 0) + 1;\n}\nvar totalBytes = parsed.reduce(function (sum, r) { return sum + (r.bytes === '-' ? 0 : Number(r.bytes)); }, 0);\nvar ips = parsed.map(function (r) { return r.ip; }).filter(function (v, i, a) { return a.indexOf(v) === i; });\nvar paths = parsed.map(function (r) { return r.path; });\n\n// Redacting the addresses with a replacement callback.\nvar redacted = lines[0].replace(/\\d+\\.\\d+\\.\\d+\\.\\d+/, function (ip) { return ip.split('.').slice(0, 2).join('.') + '.x.x'; });\n\n// A case-insensitive scan for a word anywhere in the log.\nvar hits = lines.filter(function (l) { return /alice/i.test(l); }).length;\n\n[parsed.length, bad, JSON.stringify(byStatus), totalBytes, ips.join(), paths.join(), redacted, hits].join('|');\n",
            "4|1|{\"2xx\":2,\"4xx\":1,\"5xx\":1}|1321|10.0.0.1,10.0.0.2,10.0.0.3|/index.html,/api/items,/missing,/api/items/7|10.0.x.x - alice [2024-01-02T03:04:05] \"GET /index.html HTTP/1.1\" 200 1234|2",
        ),
        Program(
            "regex_url_parser",
            "// Splits a URL into its parts, then puts a few back together.\nvar URL_RE = /^(?<scheme>[a-z][a-z0-9+.-]*):\\/\\/(?:(?<user>[^:@\\/]+)(?::(?<pass>[^@\\/]*))?@)?(?<host>[^:\\/?#]+)(?::(?<port>\\d+))?(?<path>\\/[^?#]*)?(?:\\?(?<query>[^#]*))?(?:#(?<hash>.*))?\$/;\nfunction parse(url) {\n  var m = URL_RE.exec(url);\n  if (m === null) return null;\n  var g = m.groups;\n  var out = [];\n  var keys = ['scheme', 'user', 'pass', 'host', 'port', 'path', 'query', 'hash'];\n  for (var i = 0; i < keys.length; i++) out.push(keys[i] + '=' + (g[keys[i]] === undefined ? '' : g[keys[i]]));\n  return out.join(' ');\n}\nvar a = parse('https://ann:secret@example.com:8443/a/b?x=1&y=2#frag');\nvar b = parse('http://example.com');\nvar c = parse('not a url');\n\nfunction parseQuery(q) {\n  var out = {}, re = /([^&=]+)=([^&]*)/g, m;\n  while ((m = re.exec(q)) !== null) out[decodeURIComponent(m[1])] = decodeURIComponent(m[2]);\n  return out;\n}\nvar q = parseQuery('a=1&b=two&c=%20sp%20&a=again');\n\n// Normalising a path by folding away . and .. segments.\nfunction normalize(path) {\n  var parts = path.split('/'), out = [];\n  for (var i = 0; i < parts.length; i++) {\n    if (parts[i] === '' || parts[i] === '.') continue;\n    if (parts[i] === '..') { out.pop(); continue; }\n    out.push(parts[i]);\n  }\n  return '/' + out.join('/');\n}\n\n[a, b, c, JSON.stringify(q), normalize('/a/b/../c/./d//e'), 'a/b'.replace(/\\//g, '::')].join('|');\n",
            "scheme=https user=ann pass=secret host=example.com port=8443 path=/a/b query=x=1&y=2 hash=frag|scheme=http user= pass= host=example.com port= path= query= hash=||{\"a\":\"again\",\"b\":\"two\",\"c\":\" sp \"}|/a/c/d/e|a::b",
        ),
        Program(
            "regex_validation_table",
            "// Runs a table of inputs through a table of patterns, so every cell is compared.\nvar PATTERNS = {\n  email: /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\$/,\n  hex: /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})\$/,\n  ipv4: /^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\$/,\n  isoDate: /^\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])\$/,\n  slug: /^[a-z0-9]+(?:-[a-z0-9]+)*\$/,\n  time24: /^(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?\$/,\n  identifier: /^[A-Za-z_\$][A-Za-z0-9_\$]*\$/,\n  quoted: /^\"(?:[^\"\\\\]|\\\\.)*\"\$/\n};\nvar INPUTS = [\n  'a@b.co', 'a@b', '@b.co', 'a b@c.de',\n  '#fff', '#ffffff', '#ff', '#gggggg',\n  '0.0.0.0', '255.255.255.255', '256.1.1.1', '1.2.3',\n  '2024-02-29', '2024-13-01', '2024-1-1',\n  'hello-world', 'Hello-World', 'a--b', 'a-b-c',\n  '00:00', '23:59:59', '24:00', '9:00',\n  '_x1', '1x', '\$a', 'a-b',\n  '\"ok\"', '\"esc\\\\\"\"', '\"bad', 'plain'\n];\nvar rows = [];\nvar names = Object.keys(PATTERNS).sort();\nfor (var i = 0; i < names.length; i++) {\n  var re = PATTERNS[names[i]];\n  var marks = '';\n  for (var j = 0; j < INPUTS.length; j++) marks += re.test(INPUTS[j]) ? '1' : '0';\n  rows.push(names[i] + ':' + marks);\n}\n\n// The same patterns used to extract rather than to test.\nvar found = 'mail me at a@b.co or c.d@e.fr today'.match(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}/g);\n\n// Anchors and multiline over a block of text.\nvar block = 'one\\ntwo\\nthree';\nvar starts = block.match(/^\\w+/gm);\nvar ends = block.match(/\\w+\$/gm);\n\nrows.join('|') + '#' + found.join() + '#' + starts.join() + '#' + ends.join();\n",
            "email:1000000000000000000000000000000|hex:0000110000000000000000000000000|identifier:0000000000000000000000010100001|ipv4:0000000011000000000000000000000|isoDate:0000000000001000000000000000000|quoted:0000000000000000000000000001100|slug:0000000000001111001000001010001|time24:0000000000000000000110000000000#a@b.co,c.d@e.fr#one,two,three#one,two,three",
        ),
        Program(
            "promise_task_queue",
            "// A queue that runs a fixed number of jobs at a time, built only on promises.\nfunction makeQueue(limit) {\n  var running = 0, waiting = [], log = [];\n  function pump() {\n    while (running < limit && waiting.length > 0) {\n      var job = waiting.shift();\n      running++;\n      log.push('start ' + job.name);\n      job.run().then(function (value) {\n        running--;\n        log.push('done ' + job.name + '=' + value);\n        job.settle(value);\n        pump();\n      }, function (reason) {\n        running--;\n        log.push('fail ' + job.name + '=' + reason);\n        job.fail(reason);\n        pump();\n      });\n    }\n  }\n  return {\n    add: function (name, run) {\n      var settle, fail;\n      var p = new Promise(function (res, rej) { settle = res; fail = rej; });\n      waiting.push({ name: name, run: run, settle: settle, fail: fail });\n      pump();\n      return p;\n    },\n    log: log\n  };\n}\n\nvar q = makeQueue(2);\nvar results = [];\nfunction immediate(v) { return function () { return Promise.resolve(v); }; }\nfunction broken(e) { return function () { return Promise.reject(e); }; }\n\nq.add('a', immediate(1)).then(function (v) { results.push('a:' + v); });\nq.add('b', immediate(2)).then(function (v) { results.push('b:' + v); });\nq.add('c', immediate(3)).then(function (v) { results.push('c:' + v); });\nq.add('d', broken('x')).catch(function (e) { results.push('d!' + e); });\n\n// A second queue that keeps the ordering of a chain built in a loop.\nvar chain = Promise.resolve(0);\nvar chainLog = [];\nfor (var i = 1; i <= 4; i++) {\n  (function (n) {\n    chain = chain.then(function (acc) { chainLog.push(n); return acc + n; });\n  })(i);\n}\nvar total = null;\nchain.then(function (v) { total = v; });\n\n// Nothing above has run yet: promises never call back before the turn ends.\nvar beforeDrain = [q.log.length, results.length, chainLog.length, total];\n\nPromise.resolve().then(function () {\n  // Still not everything, but enough to show the ordering is real.\n}).then(function () {}).then(function () {\n  finish();\n});\n\nvar out = [];\nfunction finish() {\n  out.push(q.log.join(','));\n  out.push(results.join(','));\n  out.push(chainLog.join(','));\n  out.push(String(total));\n}\n\nglobalThis.result = function () {\n  return [beforeDrain.join(':'), q.log.join(','), results.join(','), chainLog.join(','), String(total)].join('#');\n};\n'queued';\n\n// AFTER: globalThis.result()\n",
            "2:0:0:#start a,start b,done a=1,start c,done b=2,start d,done c=3,fail d=x#a:1,b:2,c:3,d!x#1,2,3,4#10",
        ),
        Program(
            "promise_retry_backoff",
            "// Retry with backoff, driven by a clock the test controls rather than by real time.\nfunction makeClock() {\n  var now = 0, timers = [];\n  return {\n    now: function () { return now; },\n    after: function (delay, fn) { timers.push({ at: now + delay, fn: fn }); },\n    advance: function (by) {\n      now += by;\n      timers.sort(function (a, b) { return a.at - b.at; });\n      while (timers.length > 0 && timers[0].at <= now) {\n        var t = timers.shift();\n        t.fn();\n      }\n    },\n    pending: function () { return timers.length; }\n  };\n}\n\nvar clock = makeClock();\nvar attempts = [];\n\nfunction flaky(failTimes) {\n  var seen = 0;\n  return function () {\n    seen++;\n    attempts.push(clock.now());\n    if (seen <= failTimes) return Promise.reject('fail' + seen);\n    return Promise.resolve('ok after ' + seen);\n  };\n}\n\nfunction retry(task, tries, baseDelay) {\n  return new Promise(function (resolve, reject) {\n    var attempt = 0;\n    function go() {\n      attempt++;\n      task().then(resolve, function (reason) {\n        if (attempt >= tries) { reject('gave up: ' + reason); return; }\n        clock.after(baseDelay * Math.pow(2, attempt - 1), go);\n      });\n    }\n    go();\n  });\n}\n\nvar settled = [];\nretry(flaky(2), 5, 10).then(function (v) { settled.push('A ' + v); }, function (e) { settled.push('A! ' + e); });\nretry(flaky(9), 3, 5).then(function (v) { settled.push('B ' + v); }, function (e) { settled.push('B! ' + e); });\n\n// Each advance lets the queued retries run. The timers only fire from advance, so the\n// whole thing is deterministic.\nvar steps = [];\nfunction step(by) {\n  clock.advance(by);\n  steps.push(clock.now() + ':' + clock.pending() + ':' + attempts.length);\n}\n\n// Each advance runs the retries that were waiting on it. Chaining the steps through the\n// queue keeps the whole thing deterministic.\nPromise.resolve()\n  .then(function () { step(10); })\n  .then(function () { step(20); })\n  .then(function () { step(40); })\n  .then(function () { step(80); })\n  .then(function () { step(160); })\n  .then(function () { step(320); });\n\nglobalThis.result = function () {\n  return [attempts.join(','), settled.sort().join(' / '), steps.join(' ')].join('#');\n};\n'queued';\n\n// AFTER: globalThis.result()\n",
            "0,0,10,10,30,30#A ok after 3 / B! gave up: fail3#10:0:4 30:0:6 70:0:6 150:0:6 310:0:6 630:0:6",
        ),
        Program(
            "promise_all_fetch_table",
            "// Promise.all and its friends over a table that stands in for network calls.\nvar TABLE = {\n  '/a': { ok: true, body: 'alpha' },\n  '/b': { ok: true, body: 'beta' },\n  '/c': { ok: false, body: 'not found' },\n  '/d': { ok: true, body: 'delta' }\n};\nfunction fetchPath(path) {\n  var row = TABLE[path];\n  if (row === undefined) return Promise.reject('unknown ' + path);\n  if (!row.ok) return Promise.reject(path + ': ' + row.body);\n  return Promise.resolve(row.body);\n}\n\nvar out = [];\nfunction record(label) {\n  return function (v) {\n    out.push(label + '=' + (Array.isArray(v) ? v.join(',') : String(v)));\n  };\n}\nfunction recordErr(label) {\n  return function (e) {\n    out.push(label + '!' + (e && e.name === 'AggregateError' ? e.name + '[' + e.errors.join(';') + ']' : String(e)));\n  };\n}\n\nPromise.all(['/a', '/b'].map(fetchPath)).then(record('all-ok'), recordErr('all-ok'));\nPromise.all(['/a', '/c'].map(fetchPath)).then(record('all-bad'), recordErr('all-bad'));\nPromise.allSettled(['/a', '/c'].map(fetchPath)).then(function (rs) {\n  out.push('settled=' + rs.map(function (r) { return r.status + ':' + (r.status === 'fulfilled' ? r.value : r.reason); }).join(' '));\n});\nPromise.race(['/b', '/a'].map(fetchPath)).then(record('race'), recordErr('race'));\nPromise.any(['/c', '/d'].map(fetchPath)).then(record('any'), recordErr('any'));\nPromise.any(['/c', '/zz'].map(fetchPath)).then(record('any-none'), recordErr('any-none'));\nPromise.all([]).then(record('all-empty'));\nPromise.allSettled([]).then(function (rs) { out.push('settled-empty=' + rs.length); });\n\n// Values that are not promises go through untouched.\nPromise.all([1, '/a', fetchPath('/b')]).then(record('mixed'), recordErr('mixed'));\n\n// A chain that maps over the results.\nPromise.all(['/a', '/b', '/d'].map(fetchPath))\n  .then(function (bodies) { return bodies.map(function (b) { return b.toUpperCase(); }); })\n  .then(function (upper) { return upper.join('-'); })\n  .then(record('chained'));\n\nglobalThis.result = function () { return out.sort().join('|'); };\n'queued';\n\n// AFTER: globalThis.result()\n",
            "all-bad!/c: not found|all-empty=|all-ok=alpha,beta|any-none!AggregateError[/c: not found;unknown /zz]|any=delta|chained=ALPHA-BETA-DELTA|mixed=1,/a,beta|race=beta|settled-empty=0|settled=fulfilled:alpha  rejected:/c: not found",
        ),
        Program(
            "proxy_observable_object",
            "// A small change tracker: every write, delete and read goes through a proxy that records it.\nfunction observable(target, log) {\n  return new Proxy(target, {\n    get: function (t, key) {\n      log.push('get ' + String(key));\n      return t[key];\n    },\n    set: function (t, key, value) {\n      log.push('set ' + String(key) + '=' + value);\n      t[key] = value;\n      return true;\n    },\n    deleteProperty: function (t, key) {\n      log.push('del ' + String(key));\n      delete t[key];\n      return true;\n    },\n    has: function (t, key) {\n      log.push('has ' + String(key));\n      return key in t;\n    }\n  });\n}\n\nvar log = [];\nvar state = observable({ count: 0, label: 'start' }, log);\n\nstate.count = 1;\nstate.count = state.count + 1;\nstate.label = 'middle';\nvar seenLabel = 'label' in state;\ndelete state.label;\nvar goneLabel = 'label' in state;\nstate.label = 'end';\n\nvar trail = log.join(',');\nvar target = { count: 0 };\nvar plain = observable(target, []);\nplain.count = 5;\n\n// The proxy writes through, so the target itself has changed.\nvar wroteThrough = target.count;\n\n// Reads that miss still reach the target's prototype chain.\nvar protoRead = String(state.toString).slice(0, 8);\n\n[state.count, seenLabel, goneLabel, state.label, wroteThrough, protoRead, log.length, trail].join('|');\n",
            "2|true|false|end|5|function|16|has count,set count=1,get count,has count,set count=2,has label,set label=middle,has label,del label,has label,has label,has label,set label=end",
        ),
        Program(
            "proxy_default_dict",
            "// A dictionary that answers a default instead of undefined, and hides its bookkeeping keys.\nfunction defaultDict(defaultValue) {\n  var store = {};\n  return new Proxy(store, {\n    get: function (t, key) {\n      if (key in t) return t[key];\n      if (typeof key === 'string' && key.charAt(0) === '_') return undefined;\n      return defaultValue;\n    },\n    has: function (t, key) {\n      return typeof key === 'string' && key.charAt(0) === '_' ? false : true;\n    },\n    ownKeys: function (t) {\n      var out = [];\n      var all = Object.keys(t);\n      for (var i = 0; i < all.length; i++) if (all[i].charAt(0) !== '_') out.push(all[i]);\n      return out;\n    }\n  });\n}\n\nvar counts = defaultDict(0);\nvar words = 'the cat sat on the mat the end'.split(' ');\nfor (var i = 0; i < words.length; i++) counts[words[i]] = counts[words[i]] + 1;\ncounts._internal = 'hidden';\n\nvar the = counts['the'];\nvar missing = counts['zebra'];\nvar hiddenRead = String(counts._internal);\nvar hiddenHas = '_internal' in counts;\nvar normalHas = 'cat' in counts;\nvar keys = Object.keys(counts).sort().join(',');\n\nvar totals = [];\nvar sorted = Object.keys(counts).sort();\nfor (var j = 0; j < sorted.length; j++) totals.push(sorted[j] + ':' + counts[sorted[j]]);\n\n[the, missing, hiddenRead, hiddenHas, normalHas, keys, totals.join(' ')].join('|');\n",
            "3|0|hidden|false|true|cat,end,mat,on,sat,the|cat:1 end:1 mat:1 on:1 sat:1 the:3",
        ),
        Program(
            "proxy_negative_index",
            "// Python style negative indexing on top of a normal array.\nfunction withNegativeIndex(arr) {\n  return new Proxy(arr, {\n    get: function (t, key) {\n      if (typeof key === 'string' && /^-\\d+\$/.test(key)) {\n        var i = t.length + parseInt(key, 10);\n        return i >= 0 ? t[i] : undefined;\n      }\n      return t[key];\n    },\n    set: function (t, key, value) {\n      if (typeof key === 'string' && /^-\\d+\$/.test(key)) {\n        t[t.length + parseInt(key, 10)] = value;\n        return true;\n      }\n      t[key] = value;\n      return true;\n    }\n  });\n}\n\nvar list = withNegativeIndex([10, 20, 30, 40, 50]);\nvar last = list[-1];\nvar secondLast = list[-2];\nvar tooFar = String(list[-99]);\nvar first = list[0];\nvar len = list.length;\n\nlist[-1] = 500;\nlist[1] = 200;\nlist.push(60);\n\nvar isArray = Array.isArray(list);\nvar joined = list.join(',');\nvar mapped = list.map(function (v) { return v / 10; }).join(',');\nvar sliced = list.slice(1, 3).join(',');\nvar found = list.indexOf(200);\n\n[last, secondLast, tooFar, first, len, isArray, joined, mapped, sliced, found].join('|');\n",
            "50|40|undefined|10|5|true|10,200,30,40,500,60|1,20,3,4,50,6|200,30|1",
        ),
        Program(
            "proxy_revocable_lifecycle",
            "// Handing out a capability that can be taken back later.\nfunction grant(target) {\n  var r = Proxy.revocable(target, {\n    get: function (t, key) {\n      var v = t[key];\n      return typeof v === 'function' ? v.bind(t) : v;\n    }\n  });\n  return { view: r.proxy, close: r.revoke };\n}\n\nvar account = {\n  balance: 100,\n  deposit: function (n) { this.balance += n; return this.balance; },\n  toString: function () { return 'account(' + this.balance + ')'; }\n};\n\nvar handle = grant(account);\nvar before = handle.view.balance;\nvar afterDeposit = handle.view.deposit(50);\nvar text = String(handle.view);\n\nhandle.close();\n\nfunction afterClose(fn) {\n  try {\n    return 'value:' + fn();\n  } catch (e) {\n    return e.name;\n  }\n}\n\nvar readAfter = afterClose(function () { return handle.view.balance; });\nvar writeAfter = afterClose(function () { handle.view.balance = 0; return 'wrote'; });\nvar hasAfter = afterClose(function () { return 'balance' in handle.view; });\nvar keysAfter = afterClose(function () { return Object.keys(handle.view).join(','); });\nvar deleteAfter = afterClose(function () { delete handle.view.balance; return 'deleted'; });\n\n// Revoking twice is harmless, and the target itself is untouched.\nhandle.close();\nvar targetStillFine = account.balance;\nvar closeKind = typeof handle.close;\n\n[before, afterDeposit, text, readAfter, writeAfter, hasAfter, keysAfter, deleteAfter, targetStillFine, closeKind].join('|');\n",
            "100|150|account(150)|TypeError|TypeError|TypeError|TypeError|TypeError|150|function",
        ),
        Program(
            "proxy_lazy_records",
            "// Records that build their fields the first time each one is read, using a generator as the source.\nfunction* sourceRows() {\n  yield { id: 1, kind: 'a', weight: 5 };\n  yield { id: 2, kind: 'b', weight: 3 };\n  yield { id: 3, kind: 'a', weight: 9 };\n  yield { id: 4, kind: 'c', weight: 1 };\n}\n\nfunction lazyRecord(row, work) {\n  var cache = {};\n  return new Proxy(row, {\n    get: function (t, key) {\n      if (key in t) return t[key];\n      if (Object.prototype.hasOwnProperty.call(cache, key)) return cache[key];\n      if (Object.prototype.hasOwnProperty.call(work, key)) {\n        work.calls.push(String(key) + '@' + t.id);\n        cache[key] = work[key](t);\n        return cache[key];\n      }\n      return undefined;\n    },\n    has: function (t, key) {\n      return key in t || Object.prototype.hasOwnProperty.call(work, key);\n    }\n  });\n}\n\nvar derived = {\n  calls: [],\n  label: function (r) { return r.kind.toUpperCase() + '-' + r.id; },\n  heavy: function (r) { return r.weight * r.weight * 10; }\n};\n\nvar records = [];\nfor (var row of sourceRows()) records.push(lazyRecord(row, derived));\n\nvar labels = records.map(function (r) { return r.label; }).join(',');\n// Reading the same field twice does the work only once.\nvar labelsAgain = records.map(function (r) { return r.label; }).join(',');\nvar heavyForA = records.filter(function (r) { return r.kind === 'a'; }).map(function (r) { return r.heavy; }).join(',');\nvar totalWeight = records.reduce(function (acc, r) { return acc + r.weight; }, 0);\nvar hasDerived = 'heavy' in records[0];\nvar hasNothing = 'nope' in records[0];\nvar missing = String(records[0].nope);\n\n[labels, labelsAgain, heavyForA, totalWeight, hasDerived, hasNothing, missing, derived.calls.length, derived.calls.join(' ')].join('|');\n",
            "A-1,B-2,A-3,C-4|A-1,B-2,A-3,C-4|250,810|18|true|false|undefined|6|label@1 label@2 label@3 label@4 heavy@1 heavy@3",
        ),
        Program(
            "reflect_clone",
            "// A deep copy that keeps property descriptors, built out of Reflect calls only.\nfunction cloneDeep(source, seen) {\n  if (source === null || typeof source !== 'object') return source;\n  seen = seen || [];\n  for (var s = 0; s < seen.length; s += 2) if (seen[s] === source) return seen[s + 1];\n\n  var copy = Array.isArray(source) ? [] : Object.create(Reflect.getPrototypeOf(source));\n  seen.push(source, copy);\n\n  var keys = Reflect.ownKeys(source);\n  for (var i = 0; i < keys.length; i++) {\n    var desc = Reflect.getOwnPropertyDescriptor(source, keys[i]);\n    if (desc === undefined) continue;\n    if (Reflect.has(desc, 'value')) desc.value = cloneDeep(desc.value, seen);\n    Reflect.defineProperty(copy, keys[i], desc);\n  }\n  return copy;\n}\n\nvar original = {\n  name: 'root',\n  nested: { list: [1, 2, { deep: true }], flag: false },\n  count: 3\n};\nObject.defineProperty(original, 'hidden', { value: 'x', enumerable: false, configurable: true, writable: true });\noriginal.self = original;\n\nvar copy = cloneDeep(original);\n\nvar sameShape = copy.name + ',' + copy.count + ',' + copy.nested.flag;\nvar deepValue = copy.nested.list[2].deep;\nvar independent = (function () {\n  copy.nested.list[0] = 99;\n  return original.nested.list[0] + '/' + copy.nested.list[0];\n})();\nvar cycleHeld = copy.self === copy;\nvar notShared = copy.nested !== original.nested;\nvar hiddenKept = copy.hidden;\nvar hiddenStillHidden = Object.keys(copy).indexOf('hidden');\nvar keyOrder = Reflect.ownKeys(copy).join(',');\n\n[sameShape, deepValue, independent, cycleHeld, notShared, hiddenKept, hiddenStillHidden, keyOrder].join('|');\n",
            "root,3,false|true|1/99|true|true|x|-1|name,nested,count,hidden,self",
        ),
    )
}
