/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package io.github.yuroyami.kitejs

import org.mozilla.javascript.Node as UNode

/**
 * Renders an IR tree as text so the upstream jar and the port can be compared line by line.
 *
 * `Node.toStringTree` is not used: upstream gates it behind the `rhino.printTrees` system
 * property, read once at class-init time. Walking the public API instead is reachable and says
 * exactly what is being asserted.
 */
internal object IrDump {

    /**
     * The property slots worth comparing. They drive code generation, so a difference here would
     * silently change the generated bytecode.
     */
    val intProps = listOf(
        "FUNCTION_PROP" to 1,
        "LOCAL_PROP" to 2,
        "LOCAL_BLOCK_PROP" to 3,
        "REGEXP_PROP" to 4,
        "SPECIALCALL_PROP" to 10,
        "SKIP_INDEXES_PROP" to 11,
        "INCRDECR_PROP" to 13,
        "CATCH_SCOPE_PROP" to 14,
        "MEMBER_TYPE_PROP" to 16,
        "GENERATOR_END_PROP" to 20,
        "DESTRUCTURING_ARRAY_LENGTH" to 21,
        "TEMPLATE_LITERAL_PROP" to 27,
        "TRAILING_COMMA" to 28,
        "OBJECT_LITERAL_DESTRUCTURING" to 29,
        "OPTIONAL_CHAINING" to 30,
        "SUPER_PROPERTY_ACCESS" to 31,
        "NUMBER_OF_SPREAD" to 32,
    )

    fun upstream(root: UNode?): String {
        val sb = StringBuilder()
        fun walk(n: UNode?, depth: Int) {
            if (n == null) return
            repeat(depth) { sb.append("  ") }
            sb.append(n.type)
            runCatching { n.string }.getOrNull()?.let { sb.append(" str=").append(it) }
            runCatching { n.double }.getOrNull()?.let { sb.append(" num=").append(it) }
            sb.append(" ln=").append(n.lineno).append(" col=").append(n.column)
            for ((name, slot) in intProps) {
                val v = n.getIntProp(slot, Int.MIN_VALUE)
                if (v != Int.MIN_VALUE) sb.append(' ').append(name).append('=').append(v)
            }
            sb.append('\n')
            var kid = n.firstChild
            while (kid != null) {
                walk(kid, depth + 1)
                kid = kid.next
            }
        }
        walk(root, 0)
        return sb.toString()
    }

    fun ported(root: Node?): String {
        val sb = StringBuilder()
        fun walk(n: Node?, depth: Int) {
            if (n == null) return
            repeat(depth) { sb.append("  ") }
            sb.append(n.type)
            runCatching { n.string }.getOrNull()?.let { sb.append(" str=").append(it) }
            runCatching { n.double }.getOrNull()?.let { sb.append(" num=").append(it) }
            sb.append(" ln=").append(n.lineno).append(" col=").append(n.column)
            for ((name, slot) in intProps) {
                val v = n.getIntProp(slot, Int.MIN_VALUE)
                if (v != Int.MIN_VALUE) sb.append(' ').append(name).append('=').append(v)
            }
            sb.append('\n')
            var kid = n.firstChild
            while (kid != null) {
                walk(kid, depth + 1)
                kid = kid.next
            }
        }
        walk(root, 0)
        return sb.toString()
    }

    /** Describes the first line where two dumps differ, with a little context on both sides. */
    fun describeDifference(expected: String, actual: String): String {
        val e = expected.lines()
        val a = actual.lines()
        val at = e.indices.firstOrNull { it >= a.size || e[it] != a[it] } ?: a.size
        return "differs at line ${at + 1}\n" +
            "  upstream: ${e.getOrNull(at)}\n" +
            "  ported:   ${a.getOrNull(at)}\n" +
            "  context upstream: ${e.drop(maxOf(0, at - 3)).take(7)}\n" +
            "  context ported:   ${a.drop(maxOf(0, at - 3)).take(7)}"
    }
}
